### ISSUE TITLE
Newbie local installation set up guide test

### ISSUE THREAD

**Issue by kenibarwick** [gruelbox/orko#165]
As a newbie to Orko and development world
I'd like to locally install Orko
So that I can begin to use the application 

Feature: Clean Newbie install
  Scenario: New user hasn't installed Orko before
    Given that I have a clean Windows Build
       And have no development environments (as most newbies won't have)
       And I have not installed Orko before 

    When I try to Locally install Orko using the Local install instructions
     
     Then I should be able to run the application
        And connect to one of my accounts

**Comment by badgerwithagun** [comment]
Hi Keni.

As long as you have Windows 10, you can install and run Orko [on Windows Subsystem For Linux](https://www.onmsft.com/news/how-to-install-windows-10s-linux-subsystem-on-your-pc) following the instructions on the "local install" instructions on the Wiki.  I do this myself using Ubuntu and it works perfectly.

This is just temporary. #115 covers creation of simple installers for home machines, including windows.  That's the intention.

**Comment by kenibarwick** [comment]
I like using a VM for this sort of testing 

Will be tackling #115 at some point if you like too...

**Comment by badgerwithagun** [comment]
@kenibarwick , I've added more notes to #51 about my thoughts for how these three issues cross over.  An idea I've had is that the build:

* Creates a bundle JAR (rather than deploying source code)
* Creates an installer which combines a JRE with the bundle JAR
* Creates a Dockerfile which installs alpine and the installer
* Provides a heroku yml file which deploys the Dockerfile rather than the source code directly

That way we have an (admittedly long) but clear chain which ensures that effectively all users are using the same build architecture, rather than potentially having four disparate and varyingly well-tested setups.

**Comment by badgerwithagun** [comment]
I'm working on creating a bundle JAR as part of the packaging process now. It'll make things a lot easier.

**Comment by badgerwithagun** [comment]
That's done. Now there are only two files to "install"

 - orko-app/target/orko-app.jar
 - orko-app/example-config.yml

The latter of which needs to be prompted for configuration.

**Comment by badgerwithagun** [comment]
@kenibarwick, I've revamped the instructions quite a bit on the WIki, and I think it's pretty easy now, short of actually having easy installers, which I know you're working on!

Can this be closed and the installer issue be dealt with on #115?

**Comment by kenibarwick** [comment]
for sure
